# permissions for end users to edit samples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-editor-role
rules:
- apiGroups:
  - hook.sample.kruise.io
  resources:
  - samples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hook.sample.kruise.io
  resources:
  - samples/status
  verbs:
  - get
